# Generated by Django 5.2.1 on 2025-05-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('albumid', models.AutoField(db_column='AlbumID', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('duration', models.TimeField()),
                ('credate', models.DateField(db_column='creDate')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('listenings', models.IntegerField()),
                ('genre', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'album',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Albumauthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'albumauthors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artistid', models.AutoField(db_column='ArtistID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('genre', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'artist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'liked',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listened',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'listened',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlistid', models.AutoField(db_column='PlaylistID', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('duration', models.TimeField()),
                ('credate', models.DateField(db_column='creDate')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('listenings', models.IntegerField()),
            ],
            options={
                'db_table': 'playlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playlisttrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'playlisttrack',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('trackid', models.AutoField(db_column='TrackID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('duration', models.TimeField()),
                ('releasedate', models.DateField(db_column='releaseDate')),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'track',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trackauthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'trackauthors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('login', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('regdate', models.DateField(db_column='regDate')),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
