# Generated by Django 5.2.1 on 2025-05-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={},
        ),
    ]
