# Generated by Django 5.2.1 on 2025-05-23 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_track_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tracks/'),
        ),
    ]
