# Generated by Django 5.2.1 on 2025-05-23 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_track_options_track_albumid_track_audio_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='track',
            name='albumid',
            field=models.ForeignKey(blank=True, db_column='AlbumID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.album'),
        ),
        migrations.AddField(
            model_name='track',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='track_covers/'),
        ),
    ]
